from argparse import Namespace
import random
from typing import Callable, List, Union
import torch 
import numpy as np
from torch.utils.data.dataset import Dataset
from rdkit import Chem

from .scaler import StandardScaler
from chemprop.features import get_features_generator
import pdb
from typing import List, Dict, Tuple
from chemprop.features import BatchMolGraph, get_atom_fdim, get_bond_fdim, mol2graph, get_pharm_fdim, get_react_fdim,MolGraph

class MoleculeDatapoint:
    """A MoleculeDatapoint contains a single molecule and its associated features and targets."""

    def __init__(self,
                 line: List[str],
                 args: Namespace = None,
                 features: np.ndarray = None,
                 use_compound_names: bool = False):
        """
        Initializes a MoleculeDatapoint, which contains a single molecule.

        :param line: A list of strings generated by separating a line in a data CSV file by comma.
        :param args: Arguments.
        :param features: A numpy array containing additional features (ex. Morgan fingerprint).
        :param use_compound_names: Whether the data CSV includes the compound name on each line.
        """
        if args is not None:
            self.features_generator = args.features_generator
            self.args = args
        else:
            self.features_generator = self.args = None

        if features is not None and self.features_generator is not None:
            raise ValueError('Currently cannot provide both loaded features and a features generator.')

        self.features = features

        if use_compound_names:
            self.compound_name = line[0]  # str
            line = line[1:]
        else:
            self.compound_name = None

        self.smiles = line[0]  # str
        self.mol = Chem.MolFromSmiles(self.smiles)
        

        # Generate additional features if given a generator
        if self.features_generator is not None:
            self.features = []

            for fg in self.features_generator:
                features_generator = get_features_generator(fg)
                if self.mol is not None and self.mol.GetNumHeavyAtoms() > 0:
                    self.features.extend(features_generator(self.mol))

            self.features = np.array(self.features)

        # Fix nans in features
        if self.features is not None:
            replace_token = 0
            self.features = np.where(np.isnan(self.features), replace_token, self.features)

        # Create targets
        self.targets = [float(x) if x != '' else None for x in line[1:]]
    

    def set_features(self, features: np.ndarray):
        """
        Sets the features of the molecule.

        :param features: A 1-D numpy array of features for the molecule.
        """
        self.features = features

    def num_tasks(self) -> int:
        """
        Returns the number of prediction tasks.

        :return: The number of tasks.
        """
        return len(self.targets)

    def set_targets(self, targets: List[float]):
        """
        Sets the targets of a molecule.

        :param targets: A list of floats containing the targets.
        """
        self.targets = targets

class MoleculeDatapoint_ddi:
    """A MoleculeDatapoint contains a pair of molecules (SMILES) and their associated label."""

    def __init__(self,
                 line: List[str],
                 args: Namespace = None,
                 features: np.ndarray = None,
                 use_compound_names: bool = False):
        """
        Initializes a MoleculeDatapoint, which contains a pair of molecules and their label.

        :param line: A list of strings generated by separating a line in a DDI CSV file by commas.
        :param args: Arguments (optional).
        :param features: A numpy array containing additional features (optional).
        :param use_compound_names: Whether the data CSV includes compound names (optional).
        """
        if args is not None:
            self.features_generator = args.features_generator  # 获取特征生成器
            self.args = args  # 保存参数
        else:
            self.features_generator = self.args = None

        self.features = features  # 存储特征数据

        # DDI格式包含两个SMILES（smile1, smile2）和一个label
        self.smiles1 = line[0]  # 第一个分子（smiles1）
        self.smiles2 = line[1]  # 第二个分子（smiles2）
        self.label = float(line[2]) if line[2] != '' else None  # 目标label（如0或1）

        # 使用RDKit生成每个SMILES对应的分子对象
        self.mol1 = Chem.MolFromSmiles(self.smiles1)  # 将smiles1转换为分子对象
        self.mol2 = Chem.MolFromSmiles(self.smiles2)  # 将smiles2转换为分子对象

        # 如果提供了特征生成器，则根据分子生成额外的特征
        if self.features_generator is not None:
            self.features = []  # 初始化特征列表

            for fg in self.features_generator:  # 遍历特征生成器
                features_generator = get_features_generator(fg)  # 获取特定的特征生成器
                if self.mol1 is not None and self.mol1.GetNumHeavyAtoms() > 0:
                    self.features.extend(features_generator(self.mol1))  # 为第一个分子生成特征并添加到特征列表中
                if self.mol2 is not None and self.mol2.GetNumHeavyAtoms() > 0:
                    self.features.extend(features_generator(self.mol2))  # 为第二个分子生成特征并添加到特征列表中

            self.features = np.array(self.features)  # 将特征转换为numpy数组

        # 处理特征中的NaN值，将其替换为0
        if self.features is not None:
            replace_token = 0  # 用0来替换NaN
            self.features = np.where(np.isnan(self.features), replace_token, self.features)
    def get_mol_graph(self, mol_id: int, args: Namespace, pretrain: bool, cache: Dict = None):
        """
        获取分子图,支持缓存机制
        
        :param mol_id: 1 for mol1, 2 for mol2
        :param args: 参数
        :param pretrain: 是否预训练模式
        :param cache: 缓存字典
        :return: MolGraph对象
        """
        smiles = self.smiles1 if mol_id == 1 else self.smiles2
        cached_graph = self._mol_graph1 if mol_id == 1 else self._mol_graph2
        
        # 如果已经缓存过,直接返回
        if cached_graph is not None:
            return cached_graph
        
        # 如果提供了外部缓存,检查外部缓存
        if cache is not None and smiles in cache:
            graph = cache[smiles]
        else:
            # 计算新图
            from your_module import MolGraph  # 替换为实际导入路径
            graph = MolGraph(smiles, args, pretrain, brics2emb=None)
            
            # 存入外部缓存
            if cache is not None:
                cache[smiles] = graph
        
        # 存入实例缓存
        if mol_id == 1:
            self._mol_graph1 = graph
        else:
            self._mol_graph2 = graph
        
        return graph
    def set_features(self, features: np.ndarray):
        """Sets the features for the molecule pair."""
        self.features = features  # 设置特征数据

    def num_tasks(self) -> int:
        """Returns the number of tasks (just 1 task for the DDI label)."""
        return 1  # DDI通常只有一个任务：预测分子对之间的相互作用标签

    def set_targets(self, targets: List[float]):
        """Sets the targets (labels) for the molecule pair."""
        self.label = targets[0]  # 设置标签


# class MoleculeDataset(Dataset):
#     """A MoleculeDataset contains a list of molecules and their associated features and targets."""

#     def __init__(self, data: List[MoleculeDatapoint]):
#         """
#         Initializes a MoleculeDataset, which contains a list of MoleculeDatapoints (i.e. a list of molecules).

#         :param data: A list of MoleculeDatapoints.
#         """
#         self.data = data
#         self.args = self.data[0].args if len(self.data) > 0 else None
#         self.scaler = None

#     def compound_names(self) -> List[str]:
#         """
#         Returns the compound names associated with the molecule (if they exist).

#         :return: A list of compound names or None if the dataset does not contain compound names.
#         """
#         if len(self.data) == 0 or self.data[0].compound_name is None:
#             return None

#         return [d.compound_name for d in self.data]

#     def smiles(self) -> List[str]:
#         """
#         Returns the smiles strings associated with the molecules.

#         :return: A list of smiles strings.
#         """
#         return [d.smiles for d in self.data]
#     def smiles_pair(self):
#         return [(d.smiles1,d.smiles2) for d in self.data]
    
#     def mols(self) -> List[Chem.Mol]:
#         """
#         Returns the RDKit molecules associated with the molecules.

#         :return: A list of RDKit Mols.
#         """
#         return [d.mol for d in self.data]
#     def mols_pair(self):
#         return [(d.mol1, d.mol2) for d in self.data]

#     def features(self) -> List[np.ndarray]:
#         """
#         Returns the features associated with each molecule (if they exist).

#         :return: A list of 1D numpy arrays containing the features for each molecule or None if there are no features.
#         """
#         if len(self.data) == 0 or self.data[0].features is None:
#             return None

#         return [d.features for d in self.data]

#     def targets(self) -> List[List[float]]:
#         """
#         Returns the targets associated with each molecule.

#         :return: A list of lists of floats containing the targets.
#         """
#         return [d.label for d in self.data]

#     def num_tasks(self) -> int:
#         """
#         Returns the number of prediction tasks.

#         :return: The number of tasks.
#         """
#         return self.data[0].num_tasks() if len(self.data) > 0 else None

#     def features_size(self) -> int:
#         """
#         Returns the size of the features array associated with each molecule.

#         :return: The size of the features.
#         """
#         return len(self.data[0].features) if len(self.data) > 0 and self.data[0].features is not None else None

#     def shuffle(self, seed: int = None):
#         """
#         Shuffles the dataset.

#         :param seed: Optional random seed.
#         """
#         if seed is not None:
#             random.seed(seed)
#         random.shuffle(self.data)
    
#     def normalize_features(self, scaler: StandardScaler = None, replace_nan_token: int = 0) -> StandardScaler:
#         """
#         Normalizes the features of the dataset using a StandardScaler (subtract mean, divide by standard deviation).

#         If a scaler is provided, uses that scaler to perform the normalization. Otherwise fits a scaler to the
#         features in the dataset and then performs the normalization.

#         :param scaler: A fitted StandardScaler. Used if provided. Otherwise a StandardScaler is fit on
#         this dataset and is then used.
#         :param replace_nan_token: What to replace nans with.
#         :return: A fitted StandardScaler. If a scaler is provided, this is the same scaler. Otherwise, this is
#         a scaler fit on this dataset.
#         """
#         if len(self.data) == 0 or self.data[0].features is None:
#             return None

#         if scaler is not None:
#             self.scaler = scaler

#         elif self.scaler is None:
#             features = np.vstack([d.features for d in self.data])
#             self.scaler = StandardScaler(replace_nan_token=replace_nan_token)
#             self.scaler.fit(features)

#         for d in self.data:
#             d.set_features(self.scaler.transform(d.features.reshape(1, -1))[0])

#         return self.scaler
    
#     def set_targets(self, targets: List[List[float]]):
#         """
#         Sets the targets for each molecule in the dataset. Assumes the targets are aligned with the datapoints.

#         :param targets: A list of lists of floats containing targets for each molecule. This must be the
#         same length as the underlying dataset.
#         """
#         assert len(self.data) == len(targets)
#         for i in range(len(self.data)):
#             self.data[i].set_targets(targets[i])

#     def sort(self, key: Callable):
#         """
#         Sorts the dataset using the provided key.

#         :param key: A function on a MoleculeDatapoint to determine the sorting order.
#         """
#         self.data.sort(key=key)

#     def __len__(self) -> int:
#         """
#         Returns the length of the dataset (i.e. the number of molecules).

#         :return: The length of the dataset.
#         """
#         return len(self.data)

#     def __getitem__(self, item) -> Union[MoleculeDatapoint, List[MoleculeDatapoint]]:
#         """
#         Gets one or more MoleculeDatapoints via an index or slice.

#         :param item: An index (int) or a slice object.
#         :return: A MoleculeDatapoint if an int is provided or a list of MoleculeDatapoints if a slice is provided.
#         """
#         return self.data[item]
class MoleculeDataset(Dataset):
    """A MoleculeDataset contains a list of molecule pairs and their associated features and targets."""

    def __init__(self, data: List[MoleculeDatapoint_ddi]):
        """
        Initializes a MoleculeDataset for DDI tasks.
        
        :param data: A list of MoleculeDatapoint_ddi.
        """
        self.data = data
        self.args = self.data[0].args if len(self.data) > 0 else None
        self.scaler = None

    def smiles_pair(self):
        return [(d.smiles1, d.smiles2) for d in self.data]

    def mols_pair(self):
        return [(d.mol1, d.mol2) for d in self.data]

    def features(self) -> List[np.ndarray]:
        if len(self.data) == 0 or self.data[0].features is None:
            return None
        return [d.features for d in self.data]

    def targets(self) -> List[float]:
        return [d.label for d in self.data]

    def num_tasks(self) -> int:
        return self.data[0].num_tasks() if len(self.data) > 0 else None

    def features_size(self) -> int:
        return len(self.data[0].features) if len(self.data) > 0 and self.data[0].features is not None else None

    def shuffle(self, seed: int = None):
        if seed is not None:
            random.seed(seed)
        random.shuffle(self.data)

    def normalize_features(self, scaler=None, replace_nan_token: int = 0):
        if len(self.data) == 0 or self.data[0].features is None:
            return None

        if scaler is not None:
            self.scaler = scaler
        elif self.scaler is None:
            from sklearn.preprocessing import StandardScaler
            features = np.vstack([d.features for d in self.data])
            self.scaler = StandardScaler()
            self.scaler.fit(features)

        for d in self.data:
            d.set_features(self.scaler.transform(d.features.reshape(1, -1))[0])

        return self.scaler

    def set_targets(self, targets: List[float]):
        assert len(self.data) == len(targets)
        for i in range(len(self.data)):
            self.data[i].set_targets([targets[i]])

    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, item):
        return self.data[item]

class CachedMolGraphCollator:
    """
    带缓存机制的Collate函数,用于DDI数据的批处理
    在collate过程中计算并缓存molecular graph
    """
    
    def __init__(self, args: Namespace, pretrain: bool = False, cache_size: int = 10000):
        """
        :param args: 参数
        :param pretrain: 是否预训练模式
        :param cache_size: 缓存大小(SMILES数量)
        """
        self.args = args
        self.pretrain = pretrain
        self.cache_size = cache_size
        
        # 使用字典作为LRU缓存,键是SMILES,值是MolGraph
        self._graph_cache = {}
        self._cache_order = []  # 用于LRU管理
        
    def _get_or_create_graph(self, smiles: str):
        """
        获取或创建分子图,带LRU缓存
        
        :param smiles: SMILES字符串
        :return: MolGraph对象
        """
        # 检查缓存
        if smiles in self._graph_cache:
            # 更新LRU顺序
            self._cache_order.remove(smiles)
            self._cache_order.append(smiles)
            return self._graph_cache[smiles]
        
        # 创建新图
     # 替换为实际导入路径
        mol_graph = MolGraph(smiles, self.args, self.pretrain, brics2emb=None)
        
        # 添加到缓存
        self._graph_cache[smiles] = mol_graph
        self._cache_order.append(smiles)
        
        # LRU清理:如果缓存超过限制,删除最旧的
        if len(self._cache_order) > self.cache_size:
            oldest_smiles = self._cache_order.pop(0)
            del self._graph_cache[oldest_smiles]
        
        return mol_graph
    
    def __call__(self, batch: List[MoleculeDatapoint_ddi]) -> Dict:
        """
        批处理函数,在这里计算并缓存molecular graph
        
        :param batch: 一个batch的MoleculeDatapoint_ddi列表
        :return: 包含批处理数据的字典
        """  # 替换为实际导入路径
        
        # 收集所有SMILES
        smiles1_batch = []
        smiles2_batch = []
        mol_graphs1 = []
        mol_graphs2 = []
        
        for item in batch:
            smiles1_batch.append(item.smiles1)
            smiles2_batch.append(item.smiles2)
            
            # 获取或创建分子图(带缓存)
            mol_graph1 = self._get_or_create_graph(item.smiles1)
            mol_graph2 = self._get_or_create_graph(item.smiles2)
            
            mol_graphs1.append(mol_graph1)
            mol_graphs2.append(mol_graph2)
        
        # 构建批量图
        descriptors1 = []  # 如果需要descriptor,在这里添加
        descriptors2 = []
        
        batch_graph1 = BatchMolGraph(mol_graphs1, descriptors1, self.args)
        batch_graph2 = BatchMolGraph(mol_graphs2, descriptors2, self.args)
        
        # 提取标签
        labels = torch.FloatTensor([item.label for item in batch if item.label is not None])
        
        # 提取特征(如果存在)
        features = None
        if batch[0].features is not None:
            features = torch.FloatTensor(np.vstack([item.features for item in batch]))
        
        return {
            'batch_graph1': batch_graph1,
            'batch_graph2': batch_graph2,
            'labels': labels,
            'features': features,
            'smiles1': smiles1_batch,
            'smiles2': smiles2_batch
        }
    
    def get_cache_stats(self) -> Dict:
        """获取缓存统计信息"""
        return {
            'cache_size': len(self._graph_cache),
            'cache_limit': self.cache_size,
            'cached_smiles': list(self._graph_cache.keys())[:10]  # 显示前10个
        }